#!/bin/bash

# Name: Cristian Gaudino


#read line from file
#select first letter from line
#add the word and the first letter to database

db_user="cgg1"
db_server="cs1.ucc.ie"
db_pass="weeS2dih"
db_database="2021_cgg1"
TABLE='eng_words';

input="/users/2021/cgg1/git_hub/bored_games/english.txt"
while read -r line
do
    #echo "$line" | head -c 1

    first_char=${line:0:1}
    #echo "$first_char"
    mysql --user=$db_user --password=$db_pass $db_database <<EOF
        INSERT INTO $TABLE (\`word\`, \`first_char\`) VALUES ("$line", "$first_char");
EOF
  
done < "$input"

#script to parse eng_words to each word is an update statement. run script in dbeaver
