#!/usr/local/bin/python3

print("Content-Type: text/plain\n\n")

print("<!DOCTYPE html>\n"
      "<html lang=\"en\">\n"
      "  <head>\n"
      "    <meta charset=\"utf-8\">\n"
      "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
      "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
      "    \n"
      "    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n"
      "    <title>Bored-Games</title>\n"
      "    \n"
      "    <!-- Bootstrap -->\n"
      "    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\"> \n"
      "     <link href=\"../css/styles.css\" rel=\"stylesheet\">\n"
      "\n"
      "    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n"
      "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"
      "    <!--[if lt IE 9]>\n"
      "      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n"
      "      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n"
      "    <![endif]-->\n"
      "    \n"
      "  </head>\n"
      "\n"
      "  \n"
      "  <body class=\"body\" background=\"images/theGrid4.jpg\">\n"
      "   \n"
      "    <main class=\"container\">\n"
      "    \n"
      "      <main class=\"row\">\n"
      "      <main class=\"col-md-12 \">\n"
      "      \n"
      "      </main>\n"
      "   <nav class=\"navbar navbar-inverse col-md-12\">\n"
      "  <nav class=\"container-fluid\">\n"
      "    <nav class=\"navbar-header\">\n"
      "      <a class=\"navbar-brand star\" ><p>Bored-Games</p></a>\n"
      "    </nav>\n"
      "    <nav>\n"
      "      <ul class=\"nav navbar-nav\">\n"
      "        <li class=\"active\"><a href=\"index.html\">Home</a></li>\n"
      "           <li class=\"dropdown\">\n"
      "          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Games\n"
      "          <span class=\"caret\"></span></a>\n"
      "          <ul class=\"dropdown-menu\">\n"
      "            <li><a href=\"topdown/topdown.html\">Top-Down Game</a></li>\n"
      "            <li><a href=\"hangman/index.html\">Hangman</a></li>\n"
      "            <li><a href=\"#\">Coming Soon</a></li>\n"
      "            \n"
      "          </ul>\n"
      "        </li>\n"
      "        <li class=\"dropdown\">\n"
      "          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Tutorials\n"
      "          <span class=\"caret\"></span></a>\n"
      "          <ul class=\"dropdown-menu\">\n"
      "            <li><a href=\"topdown/topdown.html\">Top-Down Game</a></li>\n"
      "            <li><a href=\"hangman/index.html\">Hangman</a></li>\n"
      "            <li><a href=\"#\">Coming Soon</a></li> \n"
      "          </ul>\n"
      "        </li>\n"
      "         \n"
      "         \n"
      "          <span class=\"caret\"></span></a>\n"
      "          \n"
      "       \n"
      "         <li><a href=\"contactUs.html\">Contact us</a></li> \n"
      "         <li><a href=\"#\">Login/Sign up</a></li>\n"
      "         <li><a href =\"#\">Sign up for our News Letter</a></li>\n"
      "         <li><form action = \"add.php\" method = \"Post\">\n"
      "          <input type = \"text\" name = \"email\" placeholder = \"E-mail Address\">\n"
      "          <input type = \"submit\"></form></li>\n"
      "      </ul>\n"
      "    </nav>\n"
      "  </nav>\n"
      "</nav>\n"
      "\n"
      "      <banner class=\"col-md-12 banner\">\n"
      "      </banner>\n"
      "\n"
      "\n"
      "     \n"
      "      </main><!--close row-->\n"
      "     \n"
      "      <div class =\"row\">\n"
      "\n"
      "        <div class=\"col-md-4\">\n"
      "\n"
      "            <h2 class=\"star\"> Top-Down Game</h2>\n"
      "             <a href=\"topdown/topdown.html\"><img class=\"img-left\" src=\"images/word1.png\"  alt=\"Top-Down Game\"/></a>\n"
      "          \n"
      "        </div><!--close col-md-8-->\n"
      "        \n"
      "        <div class =\"col-md-4\">\n"
      "        <h2 class=\"star\"><a href=\"hangman/index.html\"> Hangman </h2></a>\n"
      "        <a href=\"hangman/index.html\"><img class=\"img-left\" src=\"images/hangman1.png\"  alt=\"Hangman\"/></a>\n"
      "         \n"
      "        </div>\n"
      "\n"
      "       \n"
      "      <div class=\"row\"> \n"
      "        <div class =\"col-md-4\">\n"
      "        <h2 class=\"star\">Coming Soon</h2>\n"
      "        <img class=\"img-left\" src=\"images/coming1.png\"  alt=\"Coming Soon\"/>\n"
      "        </div> \n"
      "         </div>\n"
      "          \n"
      "                 \n"
      "         \n"
      "          </div>\n"
      "        \n"
      "\n"
      "          <nav class=\"navbar navbar-inverse col-md-12\">\n"
      "            <nav class=\"container-fluid\">\n"
      "              <div class=\"navbar-header\">\n"
      "                <nav class=\"navbar-brand star\"> &copy; Team 2 SoftWare Project 2020 all rights reserved</nav>\n"
      "              </div>\n"
      "              \n"
      "          </nav>\n"
      "\n"
      "         \n"
      "          \n"
      "          </main>\n"
      "             </div>\n"
      "            </div>\n"
      "        \n"
      "    </div><!--close container-->\n"
      "\n"
      "    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\n"
      "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n"
      "    <!-- Include all compiled plugins (below), or include individual files as needed -->\n"
      "    <script src=\"js/bootstrap.min.js\"></script>\n"
      "  </body>\n"
      "</html>")